### ISSUE TITLE
Container to Container clone does not copy across metadata/headers such as Content Type

### ISSUE THREAD

**Issue by aiman-alsari** [cloudnull/turbolift#101]
I assumed from reading some other issues that the container to container copy used some form of server side copy, which would imply that metadata was also transferred.

This does not seem to be the case. I have been copying a container full of images and their content type in the new container has been set as the default which is text/html.

**Comment by cloudnull** [comment]
what version of turbolift are you running? In turbolift 2.1.3 which is the latest stable the flag ``--clone-headers`` can be used to copy over meta data.

**Comment by aiman-alsari** [comment]
Hi cloudnull,

I did not include that flag as I thought it was the default - I shall close this issue.

Thanks

**Comment by cloudnull** [comment]
thanks @aiman-alsari -- if you have any issues let me know.

**Comment by sathyavpk** [comment]
Hello Cloudnull,
I am also facing the same issue, all the cloned images from one container to other has "Content-Type as text/html; charset=UTF-8" so its not readable over browser.

I have followed the installation details mentioned in the site to set it up. But turbolift showing the version as 3.0.0. 

  667  2015-10-13 07:13:44  git clone git://github.com/cloudnull/turbolift.git
  668  2015-10-13 07:13:44  cd turbolift
  669  2015-10-13 07:13:47  python setup.py install

[root@01-staging turbolift]# cat /etc/redhat-release
CentOS release 6.7 (Final)
[root@01-staging turbolift]# python --version
Python 2.6.6
[root@01-staging turbolift]# turbolift --version
3.0.0

I tried --clone-headers option too bu it says arguement not available

[root@01-staging turbolift]# turbolift -u uname-a api--os-rax-auth iad --clone-headers clone -sc sathyan1 -tc sathyan2 -tr iad
usage: turbolift
turbolift: error: unrecognized arguments: --clone-headers

Please help me to solve this issue :-(

Thanks,
Sathyan
