### ISSUE TITLE
Define how to use object-headers

### ISSUE THREAD

**Issue by koen-serry** [cloudnull/turbolift#79]
I've tried to set X-Expire-at by using the command-line flag --object-headers="X-Expire-at: 123" but this fails for some reason. I've looked in the python code, but I can't see where this flag is linked (although defined)

**Comment by cloudnull** [comment]
Note that the header you want to use is "X-Delete-After" or "X-Delete-At". Assuming that you want to delete an object after 123 seconds you'd use the "X-Delete-After" header. More information on that can be found here: "http://docs.openstack.org/developer/swift/overview_expiring_objects.html" Assuming you're using Rackspace Cloudfiles you can find more on that here: "http://docs.rackspace.com/files/api/v1/cf-devguide/content/Expiring_Objects-e1e3228.html"

This is what an example command would look like.
``` bash
turbolift --debug --object-headers "X-Delete-After=123" -u <USERNAME> -a <APIKEY> --os-rax-auth <REGION> upload -s <LOCAL-PATH>
```
