### ISSUE TITLE
How to purge a container from CDN

### ISSUE THREAD

**Issue by jcyin1** [cloudnull/turbolift#80]
Hello,

I'm trying to find the purge command to be able to force the Cloud Files CDN to fetch the latest file. Is there such a command available?

Thanks

**Comment by cloudnull** [comment]
You can run a purge with turbolift using the **cdn-command** function.

An example of the command would be the following

``` bash
turbolift --debug -u <USERNAME> -a <APIKEY> --os-rax-auth <REGION> cdn-command --purge <FULL-OBJECT-PATH>
```

Run this for more information on the cdn-command function:

``` bash
turbolift cdn-command --help
```
