### ISSUE TITLE
Doesn't properly follow symbolic links.

### ISSUE THREAD

**Issue by newjam** [cloudnull/turbolift#82]
Looking through the commit history and the source code, I know turbolift should support smybolic links, but in practice this isn't working for me.

Specifically I looked at turbolift/methods/__init__.py:37 where it should only be filtering out broken symlinks. But when I run turbolift, all of the symlinks in my directory don't get logged at line 97:

    report.reporter(
            msg='FILE LIST:\t%s' % f_index,
            lvl='debug',
            prt=False
        )

The use case is we "approve" content by linking it to the upload directory. We only want approved content uploaded to Rackspace.

Running Python 2.7.6

**Comment by cloudnull** [comment]
The current link process will only follow and create links on upload when the link is found within the same source path as what is being uploaded. I've changed this restriction in https://github.com/cloudnull/turbolift/tree/tbl3 branch however i've not completed that code base just yet.

**Comment by cloudnull** [comment]
Turoblift3 has become master as such this issue should be fixed. However, please feel free to reopen this issue if needed.
