### ISSUE TITLE
Limit CPU usage

### ISSUE THREAD

**Issue by patrickomeara** [cloudnull/turbolift#86]
Hey! Awesome software. Thanks.

I'm having trouble limiting the cpu usage that turbolift uses. 

I have tried using ```cpulimit`` but, I think, turbolift gets around it by using the child processes.

Any ideas?

**Comment by cloudnull** [comment]
In Turbolift you can use the ``--cc`` flag in the command line which will limit the number of concurrent threads turbolift is able to use.
