### ISSUE TITLE
Can turbolift upload only new or recently modified files in a directory?

### ISSUE THREAD

**Issue by jamiehannaford** [cloudnull/turbolift#88]
Is there a way for turbolift to only upload recently added or modified files in a local directory? I know that it supports the `tsync` operation, but for very large collections it involves a lot of unnecessary I/O that slows things down and has an effect on bandwidth charges.

I basically need to sync a local directory with Rackspace CDN. A cron job will run every minute and upload new additions or modified files. Is this supported? If so, do you recommend a best practice?

**Comment by cloudnull** [comment]
Ppresently there's nothing in turbolift that does what you've described however I should be able to add something like that in the upload option to index local files that have an mtime less than some value. Is that what you are looking for more or less?

**Comment by jamiehannaford** [comment]
Yeah, pretty much. I actually ended up using inotify in the end:

```bash
inotifywait -mr --timefmt '%d/%m/%y %H:%M' --format '%T %w %f' -e close_write /path/to/foo \
 | while read date time dir file; do
    turbolift -u foo -a bar --os-rax-auth iad upload -c baz -s $dir$file -d ${dir#$root}
  done
```

and it works pretty well. So there's no need to implement your proposed solution if there's no other need. Thanks though! :)

**Comment by cloudnull** [comment]
Great! good to hear that it worked out!
