### ISSUE TITLE
Does v3 support singular uploads?

### ISSUE THREAD

**Issue by jamiehannaford** [cloudnull/turbolift#91]
Is it possible in turbolift 3 to upload singular files? When I try `-s` with 1 file, I get:

```
Traceback (most recent call last):
  File "/usr/local/bin/turbolift", line 9, in <module>
    load_entry_point('turbolift==3.0.0', 'console_scripts', 'turbolift')()
  File "build/bdist.linux-x86_64/egg/turbolift/executable.py", line 59, in execute
  File "build/bdist.linux-x86_64/egg/turbolift/worker.py", line 130, in run_manager
  File "build/bdist.linux-x86_64/egg/turbolift/methods/upload_items.py", line 34, in start
turbolift.exceptions.DirectoryFailure: No objects found to process. Check your command.
```

The dir I'd need to reference is _huge_, so I don't want the additional bandwidth.

**Comment by cloudnull** [comment]
It is, to do so you will need to use the ``-o`` flag which will upload items provided on the command line. This option allows you to specify 1 or many files to upload that may be in different locations.

``` bash 
turbolift --color  --os-rax-auth $REGION -u $USERNAME -a $APIKEY upload -c $CONTAINERNAME -o $FILES
```

For a list of all sub argument help checkout 
``` bash 
turbolift --color  --os-rax-auth $REGION -u $USERNAME -a $APIKEY upload -h
```

**Comment by jamiehannaford** [comment]
If I use `-o` will it upload each file to its own nested pseudo-directory? For example, if I pass in:

```
foo/file1.txt
foo/bar/file2.txt
baz/file3.txt
```

will `foo`, `foo/bar` and `baz` be created as psuedo-dirs automatically? Or will there be three files at the root level? I know `-d` can specify this, but not sure how this works with multiple `-o` vals.

**Comment by cloudnull** [comment]
it will only create the object within the root directory of the container.
