### ISSUE TITLE
No  module named logger and auth takes two argument 

### ISSUE THREAD

**Issue by jayprakashstar** [cloudnull/turbolift#93]
https://github.com/cloudnull/turbolift/blob/tbl3/examples/Example_Library_Usage/upload_files.py

I am using it as sample for upload but it keeps giving these two errors

1: No module named logger from turbolift.logger import logger
2: Auth take 1 argument and  zero givem

**Comment by cloudnull** [comment]
Turbolift 3 recently became the focus of master. as such the library examples are presently being updated and will hit master soon. If you are still wanting to use turbolift stable you can install turbolift 2 from pip which will always be the source for stable installations. https://pypi.python.org/pypi/turbolift

Example command to install the last stable turbolift release.
``` bash
pip install turbolift==2.1.3
```

**Comment by jayprakashstar** [comment]
@cloudnull  Hi ,
Thanks for your quick reply. I was looking some advance feature like, to check how many turbolift instances are running currently and wait if more than certain number of instances are currently running. . Are these features available currently or not ?

**Comment by jayprakashstar** [comment]
turbolift -u user -a key --os-rax-auth dfw upload -s 25 -c container -cc 25 --error-retry 2

Giving me turbolift: error: unrecognized arguments: 25 --error-retry 2

**Comment by cloudnull** [comment]
The command syntax for upload with a concurency of 25 would be

**Comment by cloudnull** [comment]
@jayprakashstar if you wanted to check / wait for more processes to be available you can use turbolift as library however it may be easier to use bash IE: ``ps huH p $(pgrep -d" " turbolift|awk '{print $1}') | wc -l`` which will count the thread processes. However that all depends on your system and the application usage.

**Comment by jayprakashstar** [comment]
Thanks for your help. I am closing the issue.
