### ISSUE TITLE
Download files from container

### ISSUE THREAD

**Issue by fortunto2** [cloudnull/turbolift#96]
good afternoon
I need to download only some folders and files from the container
how to do it?
constantly downloaded the entire container

turbolift -u USERNAME -a APIKEY --os-rax-auth YOURDATACENTER download -c CONTAINER -s FOLDER --pattern-match '/2222/q'

or

turbolift -u USERNAME -a APIKEY --os-rax-auth YOURDATACENTER download -c CONTAINER -s FOLDER -o '/2222/q'

dont work

**Comment by cloudnull** [comment]
Please use turbolift 2.x as it is the current stable. If you installed from master using github then you are using turbolift 3 which is under ueqver development.
