### ISSUE TITLE
Unable to set header while upload

### ISSUE THREAD

**Issue by jayprakashstar** [cloudnull/turbolift#97]
Hi
I am using turbolift 2.3.1 and I tried this command while uploading
turbolift -u <USER-NAME> -a <API-KEY> --os-rax-auth <REGION> upload -s <PATH-TO-DIRECTORY> -OH Access-Control-Allow-Origin="http://example.com" -c <CONTAINER-NAME>

But I am getting error unrecognized command OH Access-Control-Allow-Origin="http://example.com"

But this works fine in turbolift 3.

But i guess turbolift is still unstable because upload is failing a lot so i m unable to use turbolift 3.
Is there any solution ?

Thanks

**Comment by jayprakashstar** [comment]
@cloudnull  please check it

**Comment by cloudnull** [comment]
@jayprakashstar sorry I've been late to reply, I'm away on vacation and won't have access to a proper computer for a bit longer. To answer your question on the state of turbolift 3 its still very much a development effort and hasnt been tagged as stable yet. Hopfully in the next few weeks I'll have time to work no it some more, to fix a few things and get it all squared away. 

As for the header use in tbl2x I believe the syntax is fully quoted string and to pass multiple headers you can use -OH multiple times. 

So this should work:
``` bash 
turbolift -u -a --os-rax-auth upload -s -OH 'Access-Control-Allow-Origin=http://example.com'
```

Let me know how it goes. I'll try to get back to you when I can but as I said I'm away and have only an old crusty HP touchpad at my disposal to stay connected , so communication may be sparse ;).

**Comment by jayprakashstar** [comment]
Hi @cloudnull  
With turbolift 2.1.3 Optional header is not working. It keeps giving unrecognized command but base header is working fine . I am using this syntax
turbolift -u  -a  --base-headers 'Access-Control-Allow-Methods=GET'   --base-headers 'Access-Control-Expose-Headers=Access-Control-Allow-Origin'  --base-headers 'Access-Control-Allow-Origin=*'  --base-headers 'Access-Control-Allow-Headers=Content-Type' --os-rax-auth dfw upload -s images -c cont

**Comment by cloudnull** [comment]
I'm sorry I should have noticed this before, however the command for headers in tbl2.x needs to go before the positional argument. 

``` bash
turbolift -u $username -a $apikey --os-rax-auth $region -OH 'Access-Control-Allow-Origin=http://example.com' upload ...
```

That should make it go. That said, I'm glad you got it to go with the use of **base-header**.
